// SpiritsCrossing — WorldTypes.cs
// Data types for the three-layer world system:
//   Ancient Ruins  — deep equilibrium echoes, violet/Source-connected
//   Newer Ruins    — partial civilizations, element-specific turbulence
//   Active Worlds  — living playspaces with NPC populations
//
// All matching ruins_data.json (generated by ruins_generator.py).

using System;
using System.Collections.Generic;
using UnityEngine;
using SpiritsCrossing.Vibration;

namespace SpiritsCrossing.World
{
    public enum WorldLayer { Ancient, Newer, Active }

    // -------------------------------------------------------------------------
    // A single ruin record
    // -------------------------------------------------------------------------
    [Serializable]
    public class RuinRecord
    {
        public string ruinId;
        public string planetId;
        public string layer;               // "Ancient" | "Newer"
        public string era;                 // e.g. "The Root Age"
        public string description;
        public VibrationalField frozenField = new VibrationalField(); // civilization's frozen vibration
        public float  discoveryThreshold;  // harmony required to perceive
        public string mythTrigger;         // myth key activated on discovery
        public float  orbitalAngleOffset;  // position around planet (radians)

        public WorldLayer Layer => layer == "Ancient" ? WorldLayer.Ancient : WorldLayer.Newer;

        /// <summary>Is this ruin harder to find than average?</summary>
        public bool IsDeep => Layer == WorldLayer.Ancient;
    }

    // -------------------------------------------------------------------------
    // Active world record — the living planet
    // -------------------------------------------------------------------------
    [Serializable]
    public class ActiveWorldRecord
    {
        public string worldId;
        public string planetId;
        public string layer = "Active";
        public string element;
        public string description;
        public float  fieldStrength;
        public float  couplingConstant;
        public string npcArchetype;
        public VibrationalField ambientField = new VibrationalField(); // current orbital equilibrium
        public float  growthRate;
        public float  discoveryThreshold = 0f; // always visible

        // Terrain regions — the physical geography of this world
        public List<TerrainRegion> terrainRegions = new List<TerrainRegion>();
    }

    // -------------------------------------------------------------------------
    // All world data for one planet
    // -------------------------------------------------------------------------
    [Serializable]
    public class PlanetWorldData
    {
        public string          planetId;
        public string          element;
        public List<RuinRecord> ancientRuins = new List<RuinRecord>();
        public List<RuinRecord> newerRuins   = new List<RuinRecord>();
        public ActiveWorldRecord activeWorld;

        /// <summary>All terrain regions across all layers of this planet.</summary>
        public List<TerrainRegion> terrainRegions = new List<TerrainRegion>();

        public List<RuinRecord> AllRuins()
        {
            var all = new List<RuinRecord>(ancientRuins);
            all.AddRange(newerRuins);
            return all;
        }
    }

    // -------------------------------------------------------------------------
    // Root collection matching ruins_data.json
    // -------------------------------------------------------------------------
    [Serializable]
    public class WorldCollection
    {
        public List<PlanetWorldData> planets        = new List<PlanetWorldData>();
        public int                   totalAncientRuins;
        public int                   totalNewerRuins;
        public int                   totalActiveWorlds;
        public string                generatedAt;

        public PlanetWorldData GetPlanet(string planetId)
        {
            foreach (var p in planets) if (p.planetId == planetId) return p;
            return null;
        }

        public RuinRecord GetRuin(string ruinId)
        {
            foreach (var p in planets)
                foreach (var r in p.AllRuins())
                    if (r.ruinId == ruinId) return r;
            return null;
        }
    }
}
