// SpiritsCrossing — ForestWorldSpawner.cs
// Manages the forest world as a living environment.
//
// RESPONSIBILITY
//   Loads forest_world_data.json (generated by forest_world_generator.py).
//   Manages zone entry/exit and coordinates between:
//     - DryadSystem       (which dryads are visible in this zone)
//     - WorldSystem       (stone ring / temple discoveries feed into ruin records)
//     - VibrationalResonanceSystem (river adjacency bonuses applied here)
//     - CompanionBehaviorController (which forest animals are active per zone)
//
// STONE RINGS
//   Overgrown ceremonial circles. On discovery, ring's frozenField merges
//   into the zone's ambient field. The altar stone (if present) grants a
//   temporary harmony boost when the player stands on it.
//
// TEMPLES
//   Multi-chamber Angkor-scale ruins. Outer threshold unlocks the approach and
//   courtyard. Inner threshold unlocks the sanctum. Each chamber discovered
//   deepens the temple's active field. Forest Hawks nest in the towers; Parrots
//   roost in causeway trees; Elder White Stag appears at dawn in the sanctum.
//
// BLESSED RIVERS
//   Linear features. While the player is within adjacencyRadius of the river,
//   green and violet bands receive passive amplification every second.
//   First contact activates the river's myth trigger.
//   Standing at the source pool activates the deeper sourcePool trigger.
//
// FOREST ANIMAL PRESENCES
//   Three forest-specific companions defined in the registry:
//     parrot           — Air / Tier 1 — roosts in causeway trees, mimics player state
//     forest_hawk      — Air / Tier 2 — nests in temple towers, circles overhead
//     elder_white_stag — Earth / Tier 3 — appears at dawn near sanctum / source pools

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using UnityEngine;
using SpiritsCrossing.Vibration;
using SpiritsCrossing.World;
using SpiritsCrossing.Companions;

namespace SpiritsCrossing.ForestWorld
{
    public class ForestWorldSpawner : MonoBehaviour
    {
        public static ForestWorldSpawner Instance { get; private set; }
        private void Awake()
        {
            if (Instance != null && Instance != this) { Destroy(gameObject); return; }
            Instance = this; DontDestroyOnLoad(gameObject);
        }

        // -------------------------------------------------------------------------
        // Inspector
        // -------------------------------------------------------------------------
        [Header("Data")]
        public string forestDataFile = "forest_world_data.json";

        [Header("River Resonance")]
        [Tooltip("How frequently (seconds) river adjacency bonuses are applied.")]
        public float riverTickInterval = 1.0f;

        [Header("Temple / Ring Discovery")]
        public float altarStandRadius  = 2.5f;  // metres — trigger altar bonus on proximity
        public float scanInterval      = 1.0f;

        [Header("Dawn Window (game-time hours, 0–24)")]
        [Tooltip("Elder White Stag appears only during this window.")]
        public float dawnStart = 5.5f;   // 5:30am
        public float dawnEnd   = 7.0f;   // 7:00am

        [Header("Debug")]
        public bool logRiverTicks     = false;
        public bool logDiscoveries    = true;
        public bool logAnimalSpawns   = true;

        // -------------------------------------------------------------------------
        // Events
        // -------------------------------------------------------------------------
        public event Action<StoneRingRecord>  OnStoneRingDiscovered;
        public event Action<TempleRecord>     OnTempleOuterDiscovered;
        public event Action<TempleRecord>     OnTempleSanctumUnlocked;
        public event Action<TempleChamber>    OnTempleChamberDiscovered;
        public event Action<BlessedRiverRecord> OnRiverFirstContact;
        public event Action<BlessedRiverRecord> OnSourcePoolReached;

        // -------------------------------------------------------------------------
        // Internal state
        // -------------------------------------------------------------------------
        public bool IsLoaded { get; private set; }
        public ForestWorldData Data { get; private set; }
        public string ActiveZoneId   { get; private set; }

        private readonly HashSet<string> _discoveredRings     = new HashSet<string>();
        private readonly HashSet<string> _discoveredTempleOuter = new HashSet<string>();
        private readonly HashSet<string> _unlockedSanctums    = new HashSet<string>();
        private readonly HashSet<string> _discoveredChambers  = new HashSet<string>();
        private readonly HashSet<string> _touchedRivers       = new HashSet<string>();
        private readonly HashSet<string> _touchedSourcePools  = new HashSet<string>();

        private float _scanTimer;
        private float _riverTimer;

        // Player transform — resolved via tag at zone entry
        private Transform _playerTransform;

        // -------------------------------------------------------------------------
        // Lifecycle
        // -------------------------------------------------------------------------
        private IEnumerator Start()
        {
            yield return LoadForestData();
        }

        private void Update()
        {
            if (!IsLoaded || string.IsNullOrEmpty(ActiveZoneId)) return;

            _scanTimer  += Time.deltaTime;
            _riverTimer += Time.deltaTime;

            if (_scanTimer >= scanInterval)
            {
                _scanTimer = 0f;
                ScanZone(ActiveZoneId);
            }

            if (_riverTimer >= riverTickInterval)
            {
                _riverTimer = 0f;
                ApplyRiverResonance(ActiveZoneId);
            }
        }

        // -------------------------------------------------------------------------
        // Loading
        // -------------------------------------------------------------------------
        private IEnumerator LoadForestData()
        {
            yield return null;
            string path = Path.Combine(Application.streamingAssetsPath, forestDataFile);
            if (!File.Exists(path))
            {
                Debug.LogWarning($"[ForestWorldSpawner] {forestDataFile} not found. " +
                                 "Run forest_world_generator.py and setup_streaming_assets.py.");
                yield break;
            }
            try
            {
                Data     = JsonUtility.FromJson<ForestWorldData>(File.ReadAllText(path));
                IsLoaded = Data != null;
                Debug.Log($"[ForestWorldSpawner] Loaded: {Data?.zones.Count} zones.");

                // Initialise DryadSystem
                if (DryadSystem.Instance != null)
                    DryadSystem.Instance.Initialise(Data);
            }
            catch (Exception e) { Debug.LogError($"[ForestWorldSpawner] Load error: {e.Message}"); }
        }

        // -------------------------------------------------------------------------
        // Zone entry / exit
        // -------------------------------------------------------------------------
        public void EnterZone(string zoneId)
        {
            ActiveZoneId      = zoneId;
            _playerTransform  = GameObject.FindGameObjectWithTag("Player")?.transform;

            DryadSystem.Instance?.EnterZone(zoneId);
            SpawnZoneAnimals(zoneId);

            var zone = Data?.GetZone(zoneId);
            Debug.Log($"[ForestWorldSpawner] Entered zone: {zoneId} " +
                      $"({zone?.zoneName ?? "?"}, element={zone?.element ?? "?"})");
        }

        public void ExitZone()
        {
            DryadSystem.Instance?.ExitZone();
            ActiveZoneId = null;
            _playerTransform = null;
        }

        // -------------------------------------------------------------------------
        // Discovery scan — rings, temples
        // -------------------------------------------------------------------------
        private void ScanZone(string zoneId)
        {
            var zone = Data?.GetZone(zoneId);
            if (zone == null) return;

            var playerField = VibrationalResonanceSystem.Instance?.PlayerField;
            if (playerField == null) return;

            // Myth modifier: environmental intensity lowers discovery barriers
            float envIntensity = UniverseStateManager.Instance?.Current.mythState.environmentalIntensity ?? 0f;
            float thresholdScale = 1f - envIntensity * 0.15f;

            // Stone rings
            foreach (var ring in zone.stoneRings)
            {
                if (_discoveredRings.Contains(ring.ringId)) continue;
                float harmony = playerField.WeightedHarmony(ring.frozenField);

                // Altar bonus: if player is near the altar stone, boost harmony
                float effectiveHarmony = harmony;
                if (ring.hasAltarStone && IsPlayerNearAltar(ring.ringId))
                {
                    effectiveHarmony = Mathf.Clamp01(harmony + ring.altarResonanceBonus);
                    DryadSystem.Instance?.ApplyAltarBonus(ring.ringId);
                }

                if (effectiveHarmony >= ring.discoveryThreshold * thresholdScale)
                    DiscoverRing(ring);
            }

            // Temples — outer and inner
            foreach (var temple in zone.temples)
            {
                float harmony = playerField.WeightedHarmony(temple.templeField);

                if (!_discoveredTempleOuter.Contains(temple.templeId) &&
                    harmony >= temple.outerDiscoveryThreshold * thresholdScale)
                    DiscoverTempleOuter(temple);

                if (_discoveredTempleOuter.Contains(temple.templeId) &&
                    !_unlockedSanctums.Contains(temple.templeId) &&
                    harmony >= temple.innerDiscoveryThreshold * thresholdScale)
                    UnlockTempleSanctum(temple);

                // Individual chambers
                foreach (var chamber in temple.chambers)
                {
                    if (_discoveredChambers.Contains(chamber.chamberId)) continue;
                    float chamberHarmony = playerField.WeightedHarmony(chamber.chamberField);
                    if (chamberHarmony >= chamber.discoveryThreshold)
                        DiscoverChamber(temple, chamber);
                }
            }
        }

        // -------------------------------------------------------------------------
        // Discovery helpers
        // -------------------------------------------------------------------------
        private void DiscoverRing(StoneRingRecord ring)
        {
            _discoveredRings.Add(ring.ringId);

            var myth = GetMythState();
            myth?.Activate(ring.mythTrigger, "ring_discovery", 0.65f);
            if (ring.hasAltarStone && !string.IsNullOrEmpty(ring.centerMythTrigger))
                myth?.Activate(ring.centerMythTrigger, "altar_stone", 0.50f);

            OnStoneRingDiscovered?.Invoke(ring);
            if (logDiscoveries)
                Debug.Log($"[ForestWorldSpawner] Stone ring discovered: {ring.ringId} " +
                          $"({ring.era}) overgrowth={ring.overgrowthLevel:F2} stones={ring.stoneCount}");
        }

        private void DiscoverTempleOuter(TempleRecord temple)
        {
            _discoveredTempleOuter.Add(temple.templeId);

            var myth = GetMythState();
            myth?.Activate(temple.outerMythTrigger, "temple_outer", 0.55f);

            OnTempleOuterDiscovered?.Invoke(temple);
            if (logDiscoveries)
                Debug.Log($"[ForestWorldSpawner] Temple approach unlocked: {temple.templeId} " +
                          $"(style={temple.templeStyle} causeway={temple.hasCauseway})");

            // Spawn hawk and parrot if temple features them
            if (temple.hawkNestPresent)   SpawnForestAnimal("forest_hawk",  temple.templeId);
            if (temple.parrotRoostPresent) SpawnForestAnimal("parrot",       temple.templeId);
        }

        private void UnlockTempleSanctum(TempleRecord temple)
        {
            _unlockedSanctums.Add(temple.templeId);

            var myth = GetMythState();
            myth?.Activate(temple.innerMythTrigger, "temple_sanctum", 0.80f);

            OnTempleSanctumUnlocked?.Invoke(temple);
            if (logDiscoveries)
                Debug.Log($"[ForestWorldSpawner] Temple sanctum unlocked: {temple.templeId}");

            // Elder White Stag appears at sanctum-level temples during dawn
            if (temple.stagAppearsAtDawn)
                TrySpawnElderWhiteStag(temple.templeId);
        }

        private void DiscoverChamber(TempleRecord temple, TempleChamber chamber)
        {
            _discoveredChambers.Add(chamber.chamberId);

            var myth = GetMythState();
            myth?.Activate(chamber.mythTrigger, "chamber_discovery", 0.60f);

            OnTempleChamberDiscovered?.Invoke(chamber);
            if (logDiscoveries)
                Debug.Log($"[ForestWorldSpawner] Chamber discovered: {chamber.chamberId} " +
                          $"({chamber.chamberName}) roots={chamber.rootDensity:F2}");
        }

        // -------------------------------------------------------------------------
        // Blessed rivers — passive resonance tick
        // -------------------------------------------------------------------------
        private void ApplyRiverResonance(string zoneId)
        {
            var zone = Data?.GetZone(zoneId);
            if (zone == null) return;
            if (_playerTransform == null) return;

            var resonance = VibrationalResonanceSystem.Instance;
            if (resonance == null) return;

            foreach (var river in zone.rivers)
            {
                if (!IsPlayerAdjacentToRiver(river)) continue;

                // Passive amplification of green and violet bands
                resonance.ApplyTransientBoost("green",  river.greenAmplification  * riverTickInterval);
                resonance.ApplyTransientBoost("violet", river.violetAmplification * riverTickInterval);

                // First contact myth
                if (!_touchedRivers.Contains(river.riverId))
                {
                    _touchedRivers.Add(river.riverId);
                    GetMythState()?.Activate(river.mythTrigger, "river_contact", 0.50f);
                    OnRiverFirstContact?.Invoke(river);
                    Debug.Log($"[ForestWorldSpawner] River first contact: {river.riverName}");
                }

                // Source pool
                if (river.hasSourcePool && IsPlayerAtSourcePool(river) &&
                    !_touchedSourcePools.Contains(river.riverId))
                {
                    _touchedSourcePools.Add(river.riverId);
                    GetMythState()?.Activate(river.sourcePoolMythTrigger, "source_pool", 0.75f);
                    OnSourcePoolReached?.Invoke(river);
                    Debug.Log($"[ForestWorldSpawner] Source pool reached: {river.riverName}");

                    if (river.stagDrinksAtSource)
                        TrySpawnElderWhiteStag(river.riverId);
                }

                if (logRiverTicks)
                    Debug.Log($"[ForestWorldSpawner] River tick: {river.riverName} " +
                              $"+green={river.greenAmplification:F3} +violet={river.violetAmplification:F3}");
            }
        }

        // -------------------------------------------------------------------------
        // Forest animal spawning
        // -------------------------------------------------------------------------
        private void SpawnZoneAnimals(string zoneId)
        {
            var zone = Data?.GetZone(zoneId);
            if (zone == null) return;

            // Parrot and Forest Hawk appear in most forest zones
            foreach (var animalId in zone.preferredCompanionIds)
            {
                if (animalId == "elder_white_stag") continue; // stag is gated by dawn + sanctum
                SpawnForestAnimal(animalId, zoneId);
            }
        }

        private void SpawnForestAnimal(string animalId, string locationContext)
        {
            var behaviorCtrl = CompanionBehaviorController.Instance;
            if (behaviorCtrl == null) return;

            behaviorCtrl.ActivateCompanion(animalId);
            if (logAnimalSpawns)
                Debug.Log($"[ForestWorldSpawner] Animal active: {animalId} at {locationContext}");
        }

        private void TrySpawnElderWhiteStag(string locationContext)
        {
            float gameHour = GetCurrentGameHour();
            bool isDawn = gameHour >= dawnStart && gameHour <= dawnEnd;

            if (isDawn)
            {
                SpawnForestAnimal("elder_white_stag", locationContext);
                Debug.Log($"[ForestWorldSpawner] Elder White Stag appears at dawn " +
                          $"(hour={gameHour:F1}) near {locationContext}");
            }
            else
            {
                Debug.Log($"[ForestWorldSpawner] Elder White Stag: not dawn " +
                          $"(hour={gameHour:F1}, window={dawnStart}–{dawnEnd}). Will appear at next dawn.");
                StartCoroutine(WaitForDawnAndSpawnStag(locationContext));
            }
        }

        private IEnumerator WaitForDawnAndSpawnStag(string locationContext)
        {
            while (true)
            {
                yield return new WaitForSeconds(30f);
                float hour = GetCurrentGameHour();
                if (hour >= dawnStart && hour <= dawnEnd)
                {
                    SpawnForestAnimal("elder_white_stag", locationContext);
                    Debug.Log($"[ForestWorldSpawner] Elder White Stag appears at dawn (deferred).");
                    yield break;
                }
            }
        }

        // -------------------------------------------------------------------------
        // Proximity helpers (scene-space — override with actual collider checks)
        // -------------------------------------------------------------------------
        private bool IsPlayerNearAltar(string ringId)
        {
            // In production: check player vs. altar stone collider tag "AltarStone_{ringId}"
            // Here: assume proximity via placeholder. Scene architect wires exact colliders.
            if (_playerTransform == null) return false;
            var altarObj = GameObject.Find($"AltarStone_{ringId}");
            if (altarObj == null) return false;
            return Vector3.Distance(_playerTransform.position, altarObj.transform.position)
                   <= altarStandRadius;
        }

        private bool IsPlayerAdjacentToRiver(BlessedRiverRecord river)
        {
            if (_playerTransform == null) return false;
            // In production: check against river spline collider tagged "River_{riverId}"
            var riverObj = GameObject.Find($"River_{river.riverId}");
            if (riverObj == null) return false;
            // Approximate: check against river object position (centroid of spline)
            return Vector3.Distance(_playerTransform.position, riverObj.transform.position)
                   <= river.adjacencyRadius;
        }

        private bool IsPlayerAtSourcePool(BlessedRiverRecord river)
        {
            if (_playerTransform == null) return false;
            var poolObj = GameObject.Find($"SourcePool_{river.riverId}");
            if (poolObj == null) return false;
            return Vector3.Distance(_playerTransform.position, poolObj.transform.position) <= 3f;
        }

        // -------------------------------------------------------------------------
        // Utility
        // -------------------------------------------------------------------------
        private SpiritsCrossing.SharedContracts.MythState GetMythState()
            => SpiritsCrossing.Runtime.UniverseStateManager.Instance?.Current.mythState;

        private float GetCurrentGameHour()
        {
            // CosmosClockSystem owns game time — delegate to it if present
            var clock = SpiritsCrossing.Autonomous.CosmosClockSystem.Instance;
            return clock != null ? clock.CurrentHour : (Time.time / 3600f % 24f);
        }

        // -------------------------------------------------------------------------
        // Public API
        // -------------------------------------------------------------------------
        public bool IsRingDiscovered(string ringId)    => _discoveredRings.Contains(ringId);
        public bool IsTempleApproached(string templeId) => _discoveredTempleOuter.Contains(templeId);
        public bool IsSanctumUnlocked(string templeId)  => _unlockedSanctums.Contains(templeId);
        public bool IsChamberDiscovered(string chamberId) => _discoveredChambers.Contains(chamberId);

        public List<StoneRingRecord> GetDiscoveredRings(string zoneId = null)
        {
            var result = new List<StoneRingRecord>();
            if (Data == null) return result;
            foreach (var z in Data.zones)
            {
                if (!string.IsNullOrEmpty(zoneId) && z.zoneId != zoneId) continue;
                foreach (var r in z.stoneRings)
                    if (_discoveredRings.Contains(r.ringId)) result.Add(r);
            }
            return result;
        }

        public List<TempleRecord> GetApproachedTemples(string zoneId = null)
        {
            var result = new List<TempleRecord>();
            if (Data == null) return result;
            foreach (var z in Data.zones)
            {
                if (!string.IsNullOrEmpty(zoneId) && z.zoneId != zoneId) continue;
                foreach (var t in z.temples)
                    if (_discoveredTempleOuter.Contains(t.templeId)) result.Add(t);
            }
            return result;
        }
    }
}
