// SpiritsCrossing — SpiritDriveProfile.cs
// Data types that mirror spirit_profiles.json (generated by spirit_profile_generator.py).
// Deserialized by SpiritProfileLoader from StreamingAssets at runtime.
// Consumed by SpiritBrainController to initialise each spirit's behavior brain.

using System;
using System.Collections.Generic;
using UnityEngine;

namespace SpiritsCrossing.SpiritAI
{
    // -------------------------------------------------------------------------
    // Drive weight distribution — output of the RBE-1 analytical computation.
    // All values sum to 1.0.
    // -------------------------------------------------------------------------
    [Serializable]
    public class SpiritDriveWeights
    {
        [Range(0f, 1f)] public float attack;
        [Range(0f, 1f)] public float flee;
        [Range(0f, 1f)] public float seek;
        [Range(0f, 1f)] public float rest;
        [Range(0f, 1f)] public float signal;
        [Range(0f, 1f)] public float explore;

        public float Get(SpiritDriveMode mode) => mode switch
        {
            SpiritDriveMode.Attack  => attack,
            SpiritDriveMode.Flee    => flee,
            SpiritDriveMode.Seek    => seek,
            SpiritDriveMode.Rest    => rest,
            SpiritDriveMode.Signal  => signal,
            SpiritDriveMode.Explore => explore,
            _                       => 0f
        };
    }

    // -------------------------------------------------------------------------
    // 7-band spectral signature — equilibrium amplitude snapshot from simulation.
    // Used to seed per-spirit visual/audio expression and portal matching.
    // -------------------------------------------------------------------------
    [Serializable]
    public class SpectralSignature
    {
        public float red;
        public float orange;
        public float yellow;
        public float green;
        public float blue;
        public float indigo;
        public float violet;

        public float GetBand(string bandName) => bandName.ToLower() switch
        {
            "red"    => red,
            "orange" => orange,
            "yellow" => yellow,
            "green"  => green,
            "blue"   => blue,
            "indigo" => indigo,
            "violet" => violet,
            _        => 0f
        };

        /// <summary>Dominant band name by amplitude.</summary>
        public string Dominant()
        {
            float best = 0f; string key = "none";
            Check("red",    red);    Check("orange", orange); Check("yellow", yellow);
            Check("green",  green);  Check("blue",   blue);   Check("indigo", indigo);
            Check("violet", violet);
            return key;
            void Check(string k, float v) { if (v > best) { best = v; key = k; } }
        }
    }

    // -------------------------------------------------------------------------
    // Per-spirit archetype profile.
    // -------------------------------------------------------------------------
    [Serializable]
    public class SpiritDriveProfile
    {
        public string         archetypeId;        // e.g. "Seated", "Dervish"
        public string         sculptureMode;       // e.g. "SeatedMeditation"
        public string         description;
        public SpiritDriveWeights driveWeights     = new SpiritDriveWeights();
        public string         dominantDrive;       // pre-computed dominant mode name
        public float          coherenceBaseline;   // 0–1 oscillator coherence
        public SpectralSignature spectralSignature = new SpectralSignature();

        public SpiritDriveMode DominantMode() =>
            Enum.TryParse<SpiritDriveMode>(Capitalise(dominantDrive), out var m) ? m : SpiritDriveMode.Rest;

        private static string Capitalise(string s) =>
            string.IsNullOrEmpty(s) ? s : char.ToUpper(s[0]) + s.Substring(1);
    }

    // -------------------------------------------------------------------------
    // Per-planet environment profile.
    // -------------------------------------------------------------------------
    [Serializable]
    public class PlanetWorldBias
    {
        [Range(0f, 1f)] public float foodRegen;
        [Range(0f, 1f)] public float hazard;
        [Range(0f, 1f)] public float signalFlow;
        [Range(0f, 1f)] public float energyRegen;
        [Range(0f, 1f)] public float signalPatch;
    }

    [Serializable]
    public class PlanetEnvironmentProfile
    {
        public string          planetId;
        public string          description;
        public PlanetWorldBias worldBias = new PlanetWorldBias();
        public List<string>    preferredArchetypes = new List<string>();
    }

    // -------------------------------------------------------------------------
    // Root collection (matches top-level JSON object).
    // -------------------------------------------------------------------------
    [Serializable]
    public class SpiritProfileCollection
    {
        public List<SpiritDriveProfile>       spirits = new List<SpiritDriveProfile>();
        public List<PlanetEnvironmentProfile> planets = new List<PlanetEnvironmentProfile>();
    }

    // -------------------------------------------------------------------------
    // Enum for the six drives — matches RBE-1 drive keys.
    // -------------------------------------------------------------------------
    public enum SpiritDriveMode
    {
        Attack,
        Flee,
        Seek,
        Rest,
        Signal,
        Explore
    }
}
