// SpiritsCrossing — CosmosGenerationData.cs
// C# data types matching cosmos_data.json (generated by rue_cosmos_generator.py).
// Loaded by CosmosGenerationSystem from StreamingAssets at runtime.

using System;
using System.Collections.Generic;
using UnityEngine;

namespace SpiritsCrossing.Cosmos
{
    // -------------------------------------------------------------------------
    // Source field parameters (RUE star model)
    // -------------------------------------------------------------------------
    [Serializable]
    public class SourceFieldConfig
    {
        public float baseEnergy      = 5.0f;
        public float flareBonus      = 10.0f;
        public float flareProbability = 0.01f;
        public float rScale          = 20.0f;   // half-power orbital radius
        public float K0              = 0.35f;   // base coupling constant

        /// <summary>Field strength F(r) at orbital radius r.</summary>
        public float FieldStrength(float r) => baseEnergy / (1f + r / rScale);

        /// <summary>Coupling constant K(r) for agents at radius r.</summary>
        public float CouplingConstant(float r) => K0 * FieldStrength(r);
    }

    // -------------------------------------------------------------------------
    // Planet spectral signature (7 bands, all 0-1)
    // -------------------------------------------------------------------------
    [Serializable]
    public class PlanetSpectralSignature
    {
        public float red;
        public float orange;
        public float yellow;
        public float green;
        public float blue;
        public float indigo;
        public float violet;

        public float GetBand(string band) => band.ToLower() switch
        {
            "red"    => red,
            "orange" => orange,
            "yellow" => yellow,
            "green"  => green,
            "blue"   => blue,
            "indigo" => indigo,
            "violet" => violet,
            _        => 0f
        };

        /// <summary>Dominant spectral band by amplitude.</summary>
        public string DominantBand()
        {
            float best = 0f; string key = "green";
            Check("red",    red);    Check("orange", orange); Check("yellow", yellow);
            Check("green",  green);  Check("blue",   blue);   Check("indigo", indigo);
            Check("violet", violet);
            return key;
            void Check(string k, float v) { if (v > best) { best = v; key = k; } }
        }
    }

    // -------------------------------------------------------------------------
    // NPC population profile for a planet
    // -------------------------------------------------------------------------
    [Serializable]
    public class NpcPopulationProfile
    {
        public float attack;
        public float flee;
        public float seek;
        public float rest;
        public float signal;
        public float explore;
        public string dominantDrive;
        public string naturalArchetype;

        public float GetDrive(string drive) => drive switch
        {
            "attack"  => attack,
            "flee"    => flee,
            "seek"    => seek,
            "rest"    => rest,
            "signal"  => signal,
            "explore" => explore,
            _         => 0f
        };
    }

    // -------------------------------------------------------------------------
    // Full generated planet configuration
    // -------------------------------------------------------------------------
    [Serializable]
    public class GeneratedPlanetConfig
    {
        public string                planetId;
        public string                element;
        public string                description;
        public float                 orbitalRadius;
        public float                 fieldStrength;
        public float                 couplingConstant;
        public PlanetSpectralSignature equilibriumSpectral = new PlanetSpectralSignature();
        public float                 equilibriumCoherence;
        public string                dominantBand;
        public string                secondaryBand;
        public NpcPopulationProfile  npcPopulation = new NpcPopulationProfile();
        public float                 growthRate;
        public List<float>           growthCurve = new List<float>();
        public float                 meanEquilibriumPhase;

        /// <summary>
        /// Logistic growth value G at session count t.
        /// G(t) = 1 / (1 + exp(-rate * (t - tHalf)))
        /// </summary>
        public float GrowthAtSession(int sessionCount, float tHalf = 25f)
        {
            float x = -growthRate * (sessionCount - tHalf);
            return 1f / (1f + Mathf.Exp(x));
        }

        /// <summary>Growth rate relative to other planets (normalized 0-1).</summary>
        public float NormalizedGrowthRate(float maxRate)
            => maxRate > 0f ? growthRate / maxRate : 0f;
    }

    // -------------------------------------------------------------------------
    // Universe synchronization model (Kuramoto order parameter)
    // -------------------------------------------------------------------------
    [Serializable]
    public class UniverseSynchronizationModel
    {
        public List<float> R_universeSamples = new List<float>();
        public float       birthThreshold;
        public float       rebirthThreshold;
        public float       meanR;
        public float       maxR;

        /// <summary>
        /// Effective K_universe boosted by the player's source connection level.
        /// As sourceConnectionLevel → 1, planets synchronize faster.
        /// </summary>
        public float EffectiveKUniverse(float sourceConnectionLevel)
            => 0.04f + sourceConnectionLevel * 0.30f;
    }

    // -------------------------------------------------------------------------
    // Root collection (matches cosmos_data.json top-level object)
    // -------------------------------------------------------------------------
    [Serializable]
    public class CosmosGenerationCollection
    {
        public SourceFieldConfig             sourceField = new SourceFieldConfig();
        public List<GeneratedPlanetConfig>   planets     = new List<GeneratedPlanetConfig>();
        public UniverseSynchronizationModel  universeSynchronization = new UniverseSynchronizationModel();
        public string                        generatedAt;

        public GeneratedPlanetConfig GetPlanet(string planetId)
        {
            foreach (var p in planets)
                if (p.planetId == planetId) return p;
            return null;
        }

        public float MaxGrowthRate()
        {
            float max = 0f;
            foreach (var p in planets) if (p.growthRate > max) max = p.growthRate;
            return max;
        }
    }
}
