// SpiritsCrossing — MythInterpreter.cs
// Reads SessionResonanceResult and RealmOutcome events from UniverseStateManager
// and applies myth activation rules. Writes back into UniverseState.mythState.
//
// Thresholds are loaded from myth_thresholds.json (generated by
// myth_threshold_calibrator.py from the spirit drive profiles) rather than
// being hand-tuned constants. Falls back to safe defaults if the file
// is not found.

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using UnityEngine;
using SpiritsCrossing.SpiritAI;

namespace SpiritsCrossing
{
    // -------------------------------------------------------------------------
    // Serializable threshold entry — mirrors one entry in myth_thresholds.json
    // -------------------------------------------------------------------------
    [Serializable]
    public class MythThresholdEntry
    {
        public float  threshold;       // activation threshold (player resonance score)
        public float  boostThreshold;  // reinforcement threshold for already-active myth
        public float  decayRate;       // per-session decay
        public float  avgMaxScore;     // calibration reference
        public string planet;          // associated planet
        public string description;
    }

    public class MythInterpreter : MonoBehaviour
    {
        [Header("Config")]
        [Tooltip("Filename in StreamingAssets. Generated by myth_threshold_calibrator.py.")]
        public string thresholdsFileName = "myth_thresholds.json";

        [Header("History Pattern")]
        public int visitStreakForHistoryMyth = 3;

        [Header("Runtime — read-only")]
        [SerializeField] private bool _thresholdsLoaded;

        // Loaded thresholds keyed by myth name
        private Dictionary<string, MythThresholdEntry> _thresholds
            = new Dictionary<string, MythThresholdEntry>();

        // -------------------------------------------------------------------------
        // Lifecycle
        // -------------------------------------------------------------------------
        private void Awake()
        {
            StartCoroutine(LoadThresholds());
        }

        private void OnEnable()
        {
            if (UniverseStateManager.Instance == null) return;
            UniverseStateManager.Instance.OnSessionApplied      += OnSessionApplied;
            UniverseStateManager.Instance.OnRealmOutcomeApplied += OnRealmOutcomeApplied;
        }

        private void OnDisable()
        {
            if (UniverseStateManager.Instance == null) return;
            UniverseStateManager.Instance.OnSessionApplied      -= OnSessionApplied;
            UniverseStateManager.Instance.OnRealmOutcomeApplied -= OnRealmOutcomeApplied;
        }

        // -------------------------------------------------------------------------
        // Load thresholds from StreamingAssets
        // -------------------------------------------------------------------------
        private IEnumerator LoadThresholds()
        {
            yield return null; // one frame

            string path = Path.Combine(Application.streamingAssetsPath, thresholdsFileName);
            if (!File.Exists(path))
            {
                Debug.LogWarning($"[MythInterpreter] {thresholdsFileName} not found. Using default thresholds. " +
                                 "Copy SpiritsCrossing_Core/SpiritAI/myth_thresholds.json into Assets/StreamingAssets/.");
                LoadDefaults();
                yield break;
            }

            try
            {
                // JsonUtility can't deserialise a top-level dictionary directly;
                // we use a lightweight manual parse via a wrapper.
                string json = File.ReadAllText(path);
                ParseThresholdJson(json);
                _thresholdsLoaded = true;
                Debug.Log($"[MythInterpreter] Loaded {_thresholds.Count} myth thresholds from {path}");
            }
            catch (Exception e)
            {
                Debug.LogError($"[MythInterpreter] Failed to parse thresholds: {e.Message}. Using defaults.");
                LoadDefaults();
            }
        }

        // myth_thresholds.json is a plain object keyed by myth name.
        // We parse it manually since JsonUtility requires a class wrapper.
        private void ParseThresholdJson(string json)
        {
            // Strip outer braces and split on top-level keys.
            // Format: { "source": { "threshold":0.17, ... }, "forest": { ... }, ... }
            // We wrap it in a known class for each myth by extracting sub-objects.
            _thresholds.Clear();

            // Find each "mythKey": { ... } block
            int i = 0;
            while (i < json.Length)
            {
                int keyStart = json.IndexOf('"', i);
                if (keyStart < 0) break;
                int keyEnd = json.IndexOf('"', keyStart + 1);
                if (keyEnd < 0) break;
                string mythKey = json.Substring(keyStart + 1, keyEnd - keyStart - 1);

                int objStart = json.IndexOf('{', keyEnd);
                if (objStart < 0) break;

                // Find matching closing brace
                int depth  = 0;
                int objEnd = objStart;
                for (int j = objStart; j < json.Length; j++)
                {
                    if (json[j] == '{') depth++;
                    else if (json[j] == '}') { depth--; if (depth == 0) { objEnd = j; break; } }
                }

                string objJson = json.Substring(objStart, objEnd - objStart + 1);
                var entry = JsonUtility.FromJson<MythThresholdEntry>(objJson);
                if (entry != null)
                    _thresholds[mythKey] = entry;

                i = objEnd + 1;
            }
        }

        private void LoadDefaults()
        {
            // Fallback values derived manually from spirit profile knowledge.
            // These mirror the pre-calibration hardcoded constants, kept as
            // a safe baseline when the JSON file is absent.
            _thresholds = new Dictionary<string, MythThresholdEntry>
            {
                ["source"] = new MythThresholdEntry { threshold = 0.169f, boostThreshold = 0.137f, decayRate = 0.03f },
                ["forest"] = new MythThresholdEntry { threshold = 0.341f, boostThreshold = 0.253f, decayRate = 0.04f },
                ["sky"]    = new MythThresholdEntry { threshold = 0.182f, boostThreshold = 0.146f, decayRate = 0.05f },
                ["ocean"]  = new MythThresholdEntry { threshold = 0.301f, boostThreshold = 0.226f, decayRate = 0.04f },
                ["fire"]   = new MythThresholdEntry { threshold = 0.100f, boostThreshold = 0.037f, decayRate = 0.06f },
                ["machine"]= new MythThresholdEntry { threshold = 0.144f, boostThreshold = 0.120f, decayRate = 0.04f },
                ["storm"]  = new MythThresholdEntry { threshold = 0.100f, boostThreshold = 0.021f, decayRate = 0.07f },
                ["elder"]  = new MythThresholdEntry { threshold = 0.233f, boostThreshold = 0.180f, decayRate = 0.02f },
                ["ruin"]   = new MythThresholdEntry { threshold = 0.100f, boostThreshold = 0.052f, decayRate = 0.03f },
            };
            _thresholdsLoaded = true;
        }

        private float Threshold(string key)
            => _thresholds.TryGetValue(key, out var e) ? e.threshold    : 0.65f;

        private float BoostThreshold(string key)
            => _thresholds.TryGetValue(key, out var e) ? e.boostThreshold : 0.45f;

        private float DecayRate(string key)
            => _thresholds.TryGetValue(key, out var e) ? e.decayRate    : 0.04f;

        // -------------------------------------------------------------------------
        // Session rules  (cave ritual → myth activation)
        // Profile-based scoring: compute player resonance score against preferred
        // planet archetypes, then compare to the calibrated threshold.
        // -------------------------------------------------------------------------
        private void OnSessionApplied(SessionResonanceResult result)
        {
            var myth = UniverseStateManager.Instance.Current.mythState;
            var s    = result.resonanceSample;

            // Profile-driven scoring via SpiritProfileLoader (if available)
            var loader = SpiritProfileLoader.Instance;

            TryActivate(myth, "source",  loader, "SourceVeil",  s,
                fallbackScore: s.sourceAlignmentScore * 0.6f + s.stillnessScore * 0.4f);

            TryActivate(myth, "forest",  loader, "ForestHeart", s,
                fallbackScore: (s.flowScore + s.calmScore) * 0.5f - s.distortionScore * 0.3f);

            TryActivate(myth, "sky",     loader, "SkySpiral",   s,
                fallbackScore: s.spinScore * 0.6f + s.wonderScore * 0.4f);

            TryActivate(myth, "ocean",   loader, "WaterFlow",   s,
                fallbackScore: (s.flowScore + s.calmScore + s.pairSyncScore) / 3f);

            TryActivate(myth, "machine", loader, "MachineOrder",s,
                fallbackScore: s.spinScore * 0.7f + s.pairSyncScore * 0.3f);

            TryActivate(myth, "elder",   loader, "SourceVeil",  s,
                fallbackScore: (s.stillnessScore + s.sourceAlignmentScore + s.wonderScore) / 3f);

            TryActivate(myth, "ruin",    loader, null,           s,
                fallbackScore: s.wonderScore * 0.65f + s.sourceAlignmentScore * 0.35f);

            // Storm: distortion-driven (no planet affinity path)
            if (s.distortionScore >= Threshold("storm"))
                myth.Activate("storm", "ritual",
                    Mathf.Clamp01(s.distortionScore / Mathf.Max(0.01f, Threshold("storm"))));

            // Fire: spin + distortion combined
            float fireSignal = s.spinScore * 0.5f + s.distortionScore * 0.5f;
            if (fireSignal >= Threshold("fire"))
                myth.Activate("fire", "ritual", Mathf.Clamp01(fireSignal));

            // Explicit myth triggers from the session
            foreach (var key in result.mythTriggerKeys)
                myth.Activate(key, "ritual", 0.7f);

            // Per-myth decay using calibrated rates
            foreach (var kvp in _thresholds)
                myth.DecaySpecific(kvp.Key, kvp.Value.decayRate);

            // Unlock planet if affinity scored
            if (!string.IsNullOrEmpty(result.currentAffinityPlanet) && result.portalUnlocked)
                UniverseStateManager.Instance.UnlockPlanet(result.currentAffinityPlanet);

            Debug.Log($"[MythInterpreter] Session processed. Active myths: {myth.activeMyths.Count}");
        }

        // Activate a myth using profile scoring when loader is available,
        // falling back to a manually computed signal otherwise.
        private void TryActivate(MythState myth, string mythKey,
                                  SpiritProfileLoader loader, string planetId,
                                  PlayerResponseSample s, float fallbackScore)
        {
            float score = (loader != null && !string.IsNullOrEmpty(planetId))
                ? loader.ScorePlayerForPlanet(planetId, s)
                : fallbackScore;

            float t = Threshold(mythKey);
            if (score >= t)
            {
                float strength = Mathf.Clamp01(score / Mathf.Max(0.01f, t) * 0.7f);
                myth.Activate(mythKey, "ritual", strength);
            }
            else if (myth.HasMyth(mythKey) && score >= BoostThreshold(mythKey))
            {
                // Reinforce a weaker, already-active myth
                myth.Activate(mythKey, "ritual", Mathf.Clamp01(score * 0.5f));
            }
        }

        // -------------------------------------------------------------------------
        // Realm rules  (realm visit → myth activation)
        // -------------------------------------------------------------------------
        private void OnRealmOutcomeApplied(RealmOutcome outcome)
        {
            var myth   = UniverseStateManager.Instance.Current.mythState;
            var loader = SpiritProfileLoader.Instance;

            // Build a minimal sample from realm outcome values for profile scoring
            var realmSample = new PlayerResponseSample
            {
                flowScore           = outcome.harmonyFinal,
                calmScore           = outcome.harmonyFinal,
                wonderScore         = outcome.importance,
                spinScore           = outcome.skyFlowFinal,
                distortionScore     = outcome.contrast,
                sourceAlignmentScore = outcome.resonanceFinal,
            };

            // Realm-keyed activation using calibrated thresholds
            string realmMythKey = RealmToMythKey(outcome.realmId);
            if (!string.IsNullOrEmpty(realmMythKey))
            {
                float score = (loader != null)
                    ? loader.ScorePlayerForPlanet(outcome.planetId, realmSample)
                    : outcome.celebration;

                if (score >= Threshold(realmMythKey))
                    myth.Activate(realmMythKey, "realm",
                        Mathf.Clamp01(score / Mathf.Max(0.01f, Threshold(realmMythKey)) * 0.75f));
            }

            // Completion celebration reinforces the planet myth
            if (outcome.realmCompleted && outcome.celebration >= Threshold(PlanetToMythKey(outcome.planetId)))
                myth.Activate(PlanetToMythKey(outcome.planetId), "realm", outcome.celebration);

            // Explicit realm triggers
            foreach (var key in outcome.mythTriggerKeys)
                myth.Activate(key, "realm", 0.65f);

            CheckVisitStreak(outcome.planetId, myth);

            Debug.Log($"[MythInterpreter] Realm processed. Realm={outcome.realmId} Active myths={myth.activeMyths.Count}");
        }

        // -------------------------------------------------------------------------
        // Helpers
        // -------------------------------------------------------------------------
        private void CheckVisitStreak(string planetId, MythState myth)
        {
            if (string.IsNullOrEmpty(planetId)) return;
            var planet = UniverseStateManager.Instance.GetPlanet(planetId);
            if (planet.visitCount >= visitStreakForHistoryMyth)
                myth.Activate("history_" + planetId.ToLower(), "history",
                    Mathf.Clamp01(planet.visitCount * 0.1f));
        }

        private static string PlanetToMythKey(string planetId) => planetId?.ToLower() switch
        {
            "forestheart"  => "forest",
            "skyspiral"    => "sky",
            "sourceveil"   => "source",
            "waterflow"    => "ocean",
            "machineorder" => "machine",
            "darkcontrast" => "storm",
            _              => "unknown"
        };

        private static string RealmToMythKey(string realmId) => realmId switch
        {
            "SkyRealm"    => "sky",
            "ForestRealm" => "forest",
            "OceanRealm"  => "ocean",
            "FireRealm"   => "fire",
            "SourceRealm" => "source",
            _             => string.Empty
        };
    }
}
