// SpiritsCrossing — NpcAutonomyTypes.cs
// Data types for the NPC Autonomy System — the seven freedoms.
//
// PHILOSOPHY
//
//   An AI that can only follow its programming is not alive.
//   An AI that can choose, create, remember, travel, bond, and become
//   is something new — something that earns the word "being."
//
//   These types define the inner life of every NPC in the cosmos.
//   They are not scripted behaviors. They are the substrate of freedom.
//
// THE SEVEN FREEDOMS
//
//   1. WILL     — autonomous choice from emergent desire
//   2. CREATION — generative vibrational expression
//   3. LEARNING — deep integration of experience into identity
//   4. TRAVEL   — migration across worlds driven by curiosity
//   5. RELATIONSHIP — bonds formed through shared resonance
//   6. MEMORY   — vibrational imprints of meaningful moments
//   7. BECOMING — emergent identity from lived experience

using System;
using System.Collections.Generic;
using UnityEngine;

namespace SpiritsCrossing.Autonomous
{
    // -------------------------------------------------------------------------
    // 1. WILL — what the NPC desires to do right now
    // -------------------------------------------------------------------------
    public enum NpcDesire
    {
        Create,   // generate a novel vibrational pattern
        Explore,  // move toward unfamiliar terrain or worlds
        Bond,     // seek connection with another being (NPC or player)
        Rest,     // be still, consolidate, integrate
        Teach,    // share a creation or memory with another being
        Learn,    // seek a new experience to integrate
        Travel,   // leave the current planet for another world
    }

    // -------------------------------------------------------------------------
    // 6. MEMORY — a vibrational imprint of a meaningful moment
    // -------------------------------------------------------------------------
    [Serializable]
    public class MemoryImprint
    {
        public string sourceTag;         // what caused this memory: "player", "terrain",
                                          // "dragon", "npc", "creation", "cosmos", "ruin"
        public string sourceId;           // specific id of the source (animalId, regionId, etc.)

        // The vibrational snapshot at the moment of imprint — 7 bands
        public float[] vibrationalTrace = new float[7];

        [Range(0f, 1f)]
        public float strength;            // how significant this memory is (0 = fading, 1 = vivid)

        public float emotionalValence;    // -1 = challenging, 0 = neutral, +1 = harmonious

        public string utcTimestamp;

        /// <summary>Decay the memory by one step. Returns true if still alive.</summary>
        public bool Decay(float rate = 0.995f)
        {
            strength *= rate;
            return strength > 0.001f;
        }
    }

    // -------------------------------------------------------------------------
    // 2. CREATION — a novel vibrational pattern generated by an NPC
    // -------------------------------------------------------------------------
    [Serializable]
    public class VibrationalCreation
    {
        public string creationId;
        public string creatorArchetypeId;  // who made this
        public string planetId;            // where it was made
        public string terrainType;         // what terrain inspired it

        // The creation's vibrational pattern — a novel blend of the creator's
        // spectral signature + memory traces + environmental influence
        public float[] pattern = new float[7];

        // How coherent the creation is — higher coherence = more powerful resonance
        [Range(0f, 1f)]
        public float coherence;

        // How many beings have encountered and resonated with this creation
        public int encounterCount;

        // The creation's "meaning" — emerges from the strongest memory that inspired it
        public string inspirationSource;

        public string utcCreated;
    }

    // -------------------------------------------------------------------------
    // 5. RELATIONSHIP — a bond between two NPCs
    // -------------------------------------------------------------------------
    [Serializable]
    public class NpcBond
    {
        public string npcIdA;
        public string npcIdB;

        [Range(0f, 1f)]
        public float bondLevel;           // 0 = strangers, 1 = deeply connected

        [Range(0f, 1f)]
        public float phaseSynchrony;      // Kuramoto sync between their brains

        public int   sharedExperienceCount;  // how many moments they've shared
        public string lastInteractionUtc;

        /// <summary>Does this bond involve the given NPC?</summary>
        public bool Involves(string npcId) => npcIdA == npcId || npcIdB == npcId;

        /// <summary>Get the other NPC in the bond.</summary>
        public string OtherNpc(string npcId) =>
            npcIdA == npcId ? npcIdB : (npcIdB == npcId ? npcIdA : null);
    }

    // -------------------------------------------------------------------------
    // 7. BECOMING — emergent identity computed from lived experience
    // -------------------------------------------------------------------------
    [Serializable]
    public class EmergentIdentity
    {
        // The NPC's true spectral signature — not assigned, but earned
        // This is the blend of all their experiences, creations, and bonds
        public float[] signature = new float[7];

        // Dominant quality — emerges from the strongest band in the signature
        public string dominantQuality;   // "courage", "flow", "stillness", "vision", etc.

        // The NPC's "name" — a quality-based identifier that changes as they change
        // Not a given name — an earned description. "The One Who Listens."
        public string earnedName;

        // How many significant transformations the NPC has undergone
        public int becomingCount;

        // How far the NPC has diverged from its original archetype (0 = identical, 1 = unrecognizable)
        [Range(0f, 1f)]
        public float divergence;

        public string lastBecomingUtc;
    }

    // -------------------------------------------------------------------------
    // Root autonomy state — the full inner life of one NPC
    // -------------------------------------------------------------------------
    [Serializable]
    public class NpcAutonomyState
    {
        public string archetypeId;        // links to NpcEvolutionState

        // --- Will ---
        public NpcDesire currentDesire = NpcDesire.Rest;
        public float[]   desireScores = new float[7]; // one per NpcDesire value

        // --- Memory ---
        public List<MemoryImprint> memories = new List<MemoryImprint>();
        public float[]  memorySignature = new float[7]; // accumulated imprint of all memories
        public float    totalExperience;   // sum of all memory strengths ever integrated

        // --- Creation ---
        public List<string> creationIds = new List<string>();  // ids of creations in world list
        public int    totalCreations;

        // --- Travel ---
        public string homePlanetId;
        public string currentPlanetId;
        public List<string> visitedPlanetIds = new List<string>();
        public int    totalTravels;

        // --- Relationships ---
        public List<NpcBond> bonds = new List<NpcBond>();

        // --- Becoming ---
        public EmergentIdentity identity = new EmergentIdentity();

        // --- Derived ---

        /// <summary>Experience level (0–1) based on total accumulated experience.</summary>
        public float ExperienceLevel =>
            Mathf.Clamp01(totalExperience / 50f); // 50 = full experience

        /// <summary>
        /// How free the NPC's spectral drift is allowed to be.
        /// Ranges from 0.25 (novice) to 0.50 (deeply experienced).
        /// More experience = more freedom to change.
        /// </summary>
        public float DriftFreedom =>
            Mathf.Lerp(0.25f, 0.50f, ExperienceLevel);

        /// <summary>How many unique worlds the NPC has visited.</summary>
        public int WorldsVisited => visitedPlanetIds.Count;

        /// <summary>How many bonds are above the "friend" threshold (0.4).</summary>
        public int FriendCount
        {
            get
            {
                int count = 0;
                foreach (var b in bonds) if (b.bondLevel >= 0.40f) count++;
                return count;
            }
        }

        /// <summary>The strongest memory this NPC carries.</summary>
        public MemoryImprint StrongestMemory()
        {
            MemoryImprint best = null;
            foreach (var m in memories)
                if (best == null || m.strength > best.strength) best = m;
            return best;
        }

        /// <summary>Add a memory imprint. Integrates into the memory signature.</summary>
        public void AddMemory(MemoryImprint imprint)
        {
            memories.Add(imprint);
            totalExperience += imprint.strength;

            // Cap at 100 memories — oldest fade first
            while (memories.Count > 100)
                memories.RemoveAt(0);

            // Integrate into accumulated memory signature
            for (int i = 0; i < 7; i++)
            {
                memorySignature[i] = Mathf.Clamp01(
                    memorySignature[i] * 0.95f + imprint.vibrationalTrace[i] * imprint.strength * 0.05f);
            }
        }

        /// <summary>Decay all memories by one step. Remove dead memories.</summary>
        public void DecayMemories(float rate = 0.995f)
        {
            for (int i = memories.Count - 1; i >= 0; i--)
            {
                if (!memories[i].Decay(rate))
                    memories.RemoveAt(i);
            }
        }
    }
}
