# Unity License Activation — run this ONCE to generate UNITY_LICENSE secret.
#
# Steps:
#   1. Go to Actions → "Acquire Unity license" → Run workflow
#   2. Download the .alf artifact from the run
#   3. Visit https://license.unity3d.com/manual and upload the .alf file
#   4. Download the returned .ulf license file
#   5. Add the file contents as a GitHub secret named UNITY_LICENSE
#      (Settings → Secrets and variables → Actions → New repository secret)
#   6. Also add UNITY_EMAIL and UNITY_PASSWORD as secrets
#
# After that this workflow is no longer needed — the ci and cd workflows
# will use the stored UNITY_LICENSE secret automatically.

name: Acquire Unity license

on:
  workflow_dispatch: {}

jobs:
  activation:
    name: Request Unity license activation file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: game-ci/unity-request-activation-file@v2
        id: getManualLicenseFile

      - uses: actions/upload-artifact@v4
        with:
          name: unity-license-activation-file
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
          retention-days: 1
